[project]
name = "open-c2e-dictionary"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "openai>=2.5.0",
    "wordfreq>=3.1.1",
]
